repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: debug-statements

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
        'flake8-blind-except',
        'flake8-bandit',
        'flake8-comprehensions',
        'flake8-mutable',
        'flake8-bugbear',
        'flake8-broken-line',
        'flake8-print',
        'flake8-pytest-style',
        ]
